configurando avaliador
betrybe/sd-0x-tech-news pull request #5
Opened 2020-11-17 13:04 UTC by brunobatista25

branch com os testes automatizados e outras configurações

2020-11-19 15:48 UTC, eucleciojosias commented on dev-requirements.txt
> +inquirer==2.7.0
```suggestion
inquirer==2.7.0
pytest-json==0.4.0
```

2020-11-19 18:16 UTC, cassiobotaro requested changes

2020-11-19 18:16 UTC, cassiobotaro commented on dev-requirements.txt
> +inquirer==2.7.0
```suggestion
```
A linha -r requirements.txt já se encarrega de instalar estas dependências.

2020-11-20 18:00 UTC, brunobatista25 commented on dev-requirements.txt
> +inquirer==2.7.0
boa vo ajustar

2020-11-28 23:47 UTC, cassiobotaro commented
Podemos fechar esta branch @brunobatista25 ?

2020-11-30 14:52 UTC, closed without merging